version: "3"

services:
  front:
    build: ./
    volumes:
      - /usr/src/app/.next
      - /usr/src/app/node_modules
      - /usr/src/app/public:/app/public
    restart: always
    ports:
      - 8000:8000

networks:
  default:
    external:
      name: iodash-net
